### ISSUE TITLE
Ideas to consider: the sugars comprising sweet-expressions

### ISSUE THREAD

**Issue by roryokane** [zackmdavis/Glitteral#1]
I don’t know your exact aims for this project, but [sweet-expressions](http://readable.sourceforge.net/) might interest you. They add [a bunch of syntactic sugar](http://sourceforge.net/p/readable/wiki/Solution/) that make S-expressions easier to read – most obviously, Python-like indentation-sensitivity. These sugars seem to fit in well with your other features, which are also syntactic sugars.

Here are possible alternative renderings of [your sample code](https://github.com/zackmdavis/Glitteral/blob/fa5e678bdea2405532b5e3a04145d16b85568129/README.md), followed by the originals. The sweet-expressions can all be automatically parsed as the same S-expressions as the originals:

``` lisp
:= glitteral_is_splendid Truth

:=λ first_plus_square_of_second |a ^int b ^int| → ^int
  + a (⋅ b b)  # This is a comment.

:= my_list [1 2 3]
append! my_list 4

if glitteral_is_splendid
  if (= first_plus_square_of_second(1 2) 5)
    _:= my_list 0 10
    print_integer 0
  print_integer 0

for |i my_list|
  print_integer i
```

> ``` lisp
> (:= glitteral_is_splendid Truth)
> 
> (:=λ first_plus_square_of_second |a ^int b ^int| → ^int
>   (+ a (⋅ b b)))  # This is a comment.
> 
> (:= my_list [1 2 3])
> (append! my_list 4)
> 
> (if glitteral_is_splendid
>   (if (= (first_plus_square_of_second 1 2) 5)
>     (_:= my_list 0 10)
>     (print_integer 0))
>   (print_integer 0))
> 
> (for |i my_list|
>   (print_integer i))
> ```

``` lisp
:=λ my_super-great_function
  "This is my function."
  |foo ^int bar ^float| → ^float
  let
    |…|
      foo_times_two (⋅ 2 foo)
      quux_of_bar (quux bar)
    ÷ foo_times_two quux_of_bar
```

> ``` lisp
> (:=λ my_super-great_function
>      "This is my function."
>      |foo ^int bar ^float| → ^float
>   (let |foo_times_two (⋅ 2 foo)
>         quux_of_bar (quux bar)|
>     (÷ foo_times_two quux_of_bar)))
> ```

When choosing how to write your code with features of sweet-expressions…
- I didn’t include curly-infix-expressions such as `{2 ⋅ foo}` in these examples, because you might want to reserve `{}` for another purpose.
- I created a symbol `|…|`, with an ellipsis character, to indicate that the indented contents should be put in `||`. You could also do it with sweet-expressions’ `\\` syntax, which wraps the contents in `()` parentheses. You would have to redefine `let` to take `()` instead of `||` if you did that.
- So that `|foo ^int bar ^float| → ^float` doesn’t get wrapped in parentheses because it’s on its own line, I assumed a new rule that says that lines beginning with data literals such as `||` aren’t wrapped in parentheses.

Sweet-expressions are backwards compatible – embedded S-expressions are still supported, even if they are multi-line. So you could also write this:

``` lisp
let
  |foo_times_two (⋅ 2 foo)
   quux_of_bar (quux bar)|
  ÷ foo_times_two quux_of_bar
```

But you wouldn’t have to support both styles of writing if you didn’t want to, since there is no Glitteral code to be backwards-compatible with.

**Comment by zackmdavis** [comment]
Wow, thanks; optional indentation-sensitive sweet-expressions look a like really great idea that I should study more and implement for Glitteral!  (I remember reading in passing that Dylan [used to be a Lisp before](http://en.wikipedia.org/wiki/History_of_the_Dylan_programming_language#The_roots_of_changing_the_syntax_from_lisp_way_to_an_infix_one) being adapted to an alternate syntax, but never looked into it and had never heard of Wheeler's sweet-expressions.)

> I don’t know your exact aims for this project

Education, [bragging rights](http://zackmdavis.net/blog/2015/05/smalltalk/), and aesthetically-pleasing-to-me-personally syntax, pursued ruthlessly and without regard for the needs of hypothetical users. (Oh, and I want to learn Rust well and rewrite it in that; the reason the pre-prototype is in Python is because I was motivated to bang out a proof-of-concept during very limited weekend hours, and Python is the only language I can write _fast_.) I'm on vacation from my dayjob the next two weeks and hope to make a lot of progress on this project (and studying [a textbook](http://www.amazon.com/Modern-Compiler-Worldwide-Computer-Science/dp/0471976970) in the hopes of having dream of a hope of a semblance of knowing what I'm doing) during that time.

> because you might want to reserve {} for another purpose.

Yeah, I'm saving braces for dictionaries.

Thanks again!! :sparkling_heart:

**Comment by zackmdavis** [comment]
(Mandatory) indentation syntax for `if`/`when`/`for`/`while`/`:=`/`_:=`/`:=λ` landed today. Not closing this ticket just yet because I also want to do the `[…]`/`|…|`/`{…}`/`<…>` thing.

**Comment by zackmdavis** [comment]
```
zmd@ExpectedReturn:~/Code/Glitteral/preprototype$ cat demo.gltrl 
:= block_list_literal […]—
   "if"
   "this"
   "works,"
   "then"

:= block_dictionary_literal {…}—
   "close issue #" 1;
   "foo bar quux" 2;

for |i (range 0 4)|—
   (println (_ block_list_literal i))

:= key "close issue #"
(println key)
(println (_ block_dictionary_literal key))
zmd@ExpectedReturn:~/Code/Glitteral/preprototype$ ./glitteralc demo.gltrl 
zmd@ExpectedReturn:~/Code/Glitteral/preprototype$ ./demo 
if
this
works,
then
close issue #
1
```
